name: env
channels:
  - defaults
dependencies:
  - numpy=1.26.3
  - pandas=2.1.4
  - pip=23.2.1
  - python=3.11.5
  - tqdm=4.66.1
  - pip:
      - matplotlib==3.8.2
      - azure-ai-ml==1.12.1
      - azure-identity==1.15.0
      - azure-core==1.29.6
      - azureml==0.2.7
      - azureml-mlflow==1.53.0
      - jupyterlab==4.0.7
      - torch==2.1.2
      - torchmetrics==1.2.1
      - lightning==2.1.3
      - lightning-utilities==0.10.0
      - mlflow==2.7.1
      - pre-commit==3.5.0
      - typer==0.9.0
      - pycocotools==2.0.7